-- ============================================================
-- Reflex — 0007_portfolios.sql
-- Portfolio index as data (was a hardcoded array in apps/api/src/portfolio.ts).
-- Mirrors the table ALREADY LIVE in Neon (created by hand): columns and the integer
-- serial `id` match the real table exactly, verified against information_schema.
--   id integer serial pk · portfolio_title text · tools_used text ·
--   page_number integer · position integer · created_at/updated_at timestamptz
-- The four content columns are rendered into the prompt's PORTFOLIO_INDEX string
-- (`N. portfolio_title — tools_used — page {page_number}, position {position}`), ordered
-- page_number ASC, position ASC, and managed from the portal's Portfolio tab.
--
-- Idempotent + non-destructive (the live table already exists with 74 rows):
--   * `create table if not exists` — no-op against the live table; recreates it on a fresh DB.
--   * the seed only inserts when the table is empty, so it never touches existing rows.
--
-- Append-only migration. Apply with OWNER creds in your own terminal:
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f migrations/0007_portfolios.sql
-- ============================================================

create table if not exists portfolios (
  id              integer     generated by default as identity primary key,
  portfolio_title text        not null,
  tools_used      text        not null,
  page_number     integer     not null,
  position        integer     not null,
  created_at      timestamptz default now(),
  updated_at      timestamptz default now()
);

-- Fast ordered reads for both the table view and the index build.
create index if not exists portfolios_order_idx on portfolios (page_number, position);

-- Seed the 74 items ONLY when the table is empty (page_number, position match the historical
-- hardcoded index exactly). No-op against the live table (already 74 rows).
insert into portfolios (portfolio_title, tools_used, page_number, position)
select * from (values
  ('AI Gift Recommendation Engine', 'Claude + FastAPI + Prompt Engineering', 1, 1),
  ('Medical-Legal Document Automation with the Anthropic API', 'Claude + n8n + Airtable', 1, 2),
  ('CRM + PM Platform That Self-Supervises via Claude SDK', 'Claude + Supabase + React', 1, 3),
  ('Work Witness — Full SaaS Built AI-Native with Claude Code', 'Claude Code + Full-Stack Development + AI Implementation', 1, 4),
  ('Automated Executive Reporting with Claude Cowork and Monday.com', 'Claude Cowork + Monday.com MCP + Business Reporting', 1, 5),
  ('RAG (Claude): Three-Agent Public-Sector Bidding Engine', 'Claude + RAG + Supabase pgvector + Python', 1, 6),
  ('Claude Code: AI Recruitment Operating System Built End-to-End', 'Claude Code + React + FastAPI + Supabase', 1, 7),
  ('24/7 AI-Powered Real Estate Lead Qualification & Management System', 'VAPI.ai + Make.com + Twilio', 1, 8),
  ('AI Voice Automated Professional Appointment Reminder System', 'n8n + Google Calendar + VAPI', 1, 9),
  ('AI-Powered Chat-to-Calendar Appointment Booking Automation', 'ChatGPT + Google Calendar + Scheduling', 1, 10),
  ('AI Executive Assistant for Email & Calendar Management', 'Relevance AI + Make.com + Slack + Gmail', 2, 1),
  ('Smart & Dynamic AI WhatsApp Chatbot - Sales + Customer Support', 'ChatGPT + WhatsApp Business API + Make.com', 2, 2),
  ('AI-Powered Customer Communication & Data Management System', 'OpenAI + Gmail + Google Sheets + Google Docs', 2, 3),
  ('Quickbooks - Financial Dashboard & Reporting - Looker Studio, Power BI', 'QuickBooks Online + Looker Studio + Power BI', 2, 4),
  ('AI-Powered Passport Data Extraction Document Processing Solution', 'Google Cloud Vision OCR + ChatGPT + Make.com', 2, 5),
  ('Personalized COLD E-Mail Automation = Target + Prospect + Custom Mail', 'LinkedIn Sales Navigator + ChatGPT + Make.com', 2, 6),
  ('Google Maps Lead Generator Via Apify Web Scraping Automation', 'Apify + n8n + Google Sheets', 2, 7),
  ('Automated Newsletter Production Pipeline', 'Multi-agent AI + n8n + Google Docs', 2, 8),
  ('Multi-Platform Social Media Automation with Google Sheets Management', 'Make.com + Instagram + Facebook + LinkedIn', 2, 9),
  ('Intelligent Email Trading Signal Processor with Alpaca Integration', 'Gmail + Alpaca API + Make.com', 2, 10),
  ('AI-Powered HR Recruitment Automation with Voice Assistant Integration', 'n8n + VAPI + ChatGPT + Google Sheets', 3, 1),
  ('AI-Powered Trading Blog Content Generator with SEO Optimization', 'n8n + ChatGPT + SEO', 3, 2),
  ('AI-Powered RSS Feed-to-Email Campaign Generator', 'RSS + OpenAI + Notion + Gmail', 3, 3),
  ('AI-Powered SEO Content Generator with Google Sheets Integration', 'n8n + ChatGPT + Google Sheets', 3, 4),
  ('AI-Powered Video Creation Automation via Telegram Integration', 'Telegram + n8n + AI image/audio generation', 3, 5),
  ('AI-Powered Product Research Automation with Amazon Data Integration', 'Make.com + Amazon data scraping + OpenAI', 3, 6),
  ('AI-Powered Email Management System for Outlook and Slack Integration', 'Make.com + Outlook + Slack + OpenAI', 3, 7),
  ('End-to-End Receipt Processing Automation with Make.com Integration', 'Make.com + QuickBooks + Xero + FreshBooks', 3, 8),
  ('Real-Time Project Management Sync Google Sheets & ClickUp Workflow', 'Google Sheets + ClickUp + Make.com', 3, 9),
  ('n8n + RSS Feed Associated LinkedIn Job Search Strategy Automation', 'n8n + RSS + OpenAI + LinkedIn', 3, 10),
  ('Automated Customer Sentiment Tracking via Gmail & monday.com', 'Gmail + ChatGPT + Monday.com + NLP', 4, 1),
  ('AI-Powered Telegram Trading Bot Technical Chart Analysis Automation', 'Telegram + ChatGPT + market data analysis', 4, 2),
  ('AI-Powered WhatsApp Chat Management & Analyzation with PDF.co', 'Unipile + ChatGPT + PDF.co + Make.com', 4, 3),
  ('n8n + Google Drive Automated Content Management System', 'n8n + Google Drive API + AI agents', 4, 4),
  ('Restaurant Orders Automated Through AI Voice Assistant Ordering', 'VAPI + Twilio + Make.com', 4, 5),
  ('AI Voice-Powered Multi-Platform Content Marketing Automation', 'Telegram + OpenAI + image generation', 4, 6),
  ('Telegram-to-Outlook Automation Email & Calendar Management System', 'n8n + Microsoft Outlook + Telegram', 4, 7),
  ('Google Credentials Integration via n8n Workflow Automation', 'n8n + Google Drive + Gmail + Sheets OAuth2', 4, 8),
  ('AI-Powered Cold Email Data Generator', 'n8n + dual OpenAI models + Google Sheets', 4, 9),
  ('Advanced n8n Recruitment Process Automation', 'n8n + Gmail + Google Sheets + OpenAI', 4, 10),
  ('Telegram & Google Calendar Integrated Automation System', 'Telegram + Google Calendar + n8n', 5, 1),
  ('RSS Feed Automation for Content Writing and Email Notifications', 'n8n + RSS + Notion + Gmail', 5, 2),
  ('n8n SEO-Optimized Content Creation and Management System', 'n8n + SEO + Google Drive', 5, 3),
  ('AI-Powered Email Classification & Management with n8n', 'n8n + Microsoft Outlook + Airtable + ChatGPT', 5, 4),
  ('ManyChat + ChatGPT + Slack + Make.com Integration | Automated Chatbot', 'ManyChat + ChatGPT + Slack + Make.com', 5, 5),
  ('Generate Questions and Answers from your Notes | Make.com Automation', 'Make.com + Google Drive', 5, 6),
  ('Automated Social Media: Content Creation and Scheduling with Make.com', 'Make.com + Social Media Management + API Integration + Content Creation', 5, 7),
  ('ManyChat Automation: PayPal / Venmo Payout via Chat', 'ManyChat + PayPal + Venmo', 5, 8),
  ('Elevate Your SMS Campaigns: Twilio SMS Automation on Make.com', 'Twilio + Make.com + Google Apps Script', 5, 9),
  ('Attendance Management Automation: System for Precision on Make.com', 'E-time office + Make.com + WhatsApp', 5, 10),
  ('Google Reviews Reply Automation: Make.com Automation', 'Make.com + ChatGPT + WhatsApp', 6, 1),
  ('Instagram Data Scraping Automation with Make.com', 'Make.com + Google Sheets + Instagram scraping', 6, 2),
  ('Speech-to-Speech Telegram AI Bot: ChatGPT + Eleven Labs | Python Bot', 'Telegram + ChatGPT + Whisper + Eleven Labs + Python', 6, 3),
  ('Seamless Integration of Survey Monkey and Make.com | Survey Automation', 'SurveyMonkey + Make.com + Google Sheets', 6, 4),
  ('Quickbooks - Automated InterCompany Invoice Creation', 'QuickBooks Online + Make.com', 6, 5),
  ('Automated Migration from Google Drive to Frame.io | Python | S3 Bucket', 'Python + Google Drive + Frame.io + S3', 6, 6),
  ('Job Scraping Automation using APIFY + Airtable + Make.com | API | AI', 'Apify + Airtable + Make.com', 6, 7),
  ('Automated Messages with Google Sheet, AppScript, & Twilio on Make.com', 'Google Apps Script + Twilio + Make.com', 6, 8),
  ('E-Commerce Order Fulfillment Automation: A Case Study', 'Make.com + CRM Automation + Ecommerce', 6, 9),
  ('Task Management Automation using Google Apps Script and Make.com', 'Google Apps Script + Make.com + WhatsApp API', 6, 10),
  ('Quickbooks - InterCompany Product Sync Automation', 'QuickBooks Online + multi-channel sync (Amazon/Shopify/Walmart)', 7, 1),
  ('ManyChat Workflow Expert - Make.com, ChatGPT and Klaviyo Integration', 'ManyChat + Klaviyo + ChatGPT + Make.com', 7, 2),
  ('Image-To-Text Automation | OCR Automation | Make.com Automation | API', 'Google Cloud Vision + Make.com + Google Sheets', 7, 3),
  ('Google Apps Script - Auto-populate your Formulas in New Rows on Sheets', 'Google Apps Script + Google Sheets', 7, 4),
  ('Custom App Creation for Abaninja and Zapfloor: Make.com Automation', 'Make.com + custom app integration', 7, 5),
  ('Automated SEO-Friendly Articles | Make.com Automation | WordPress + AI', 'ChatGPT + Make.com + WordPress + Google Sheets', 7, 6),
  ('Automating Email Communication: ChatGPT Email Automation on Make.com', 'Gmail + ChatGPT + Make.com', 7, 7),
  ('Quickbooks - Chart of Account Setup (Advanced Level)', 'QuickBooks Online + Financial Reporting + Accounting', 7, 8),
  ('Order Management Make.com Automation: SOS & Pacejet Integration', 'SOS OMS + Pacejet + Make.com', 7, 9),
  ('Quickbooks Automaton on Make.com | QBO Make.com Automation', 'QuickBooks Online + Make.com + API Integration', 7, 10),
  ('Weekly KPI & Performance Tracking Automation', 'Make.com + Google Sheets dashboards', 8, 1),
  ('Automating Sample Testing Funnel: From Lead Capturing to Feedback', 'GetResponse + SlickText + SignNow + Make.com', 8, 2),
  ('Personalized Nutrition Plan Automation - plans your client''s Nutrition', 'Make.com + Zapier + Jotform + Google Docs', 8, 3),
  ('Website Screenshot Management with Seamless Automation - URLBOX.IO', 'URLBOX.IO + Google Sheets', 8, 4)
) as seed(portfolio_title, tools_used, page_number, position)
where not exists (select 1 from portfolios);
